"""add_working_directory_to_boards

Revision ID: be04ffcfddf1
Revises: 003_agent_execution
Create Date: 2026-02-04 21:14:53.690355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be04ffcfddf1'
down_revision: Union[str, None] = '003_agent_execution'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_executions', 'workflow_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='development, quick_development, architecture_only',
               existing_nullable=False)
    op.alter_column('agent_executions', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pending, running, completed, failed, cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('agent_executions', 'current_phase',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Current workflow phase: architecture, development, review',
               existing_nullable=True)
    op.alter_column('agent_executions', 'iteration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Current iteration count for feedback loops',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_executions', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Execution context and configuration',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_executions', 'result_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Summary of execution results',
               existing_nullable=True)
    op.alter_column('agent_outputs', 'agent_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='software-architect, software-developer, code-reviewer, queen-coordinator',
               existing_nullable=False)
    op.alter_column('agent_outputs', 'phase',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='architecture, development, review',
               existing_nullable=False)
    op.alter_column('agent_outputs', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pending, running, completed, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('agent_outputs', 'input_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Input provided to the agent',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_outputs', 'output_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Raw text output from the agent',
               existing_nullable=True)
    op.alter_column('agent_outputs', 'output_structured',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Parsed structured output',
               existing_nullable=True)
    op.alter_column('agent_outputs', 'files_created',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of files created/modified by agent',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_outputs', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total tokens used in this agent call',
               existing_nullable=True)
    op.alter_column('agent_outputs', 'duration_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Execution duration in milliseconds',
               existing_nullable=True)
    op.add_column('boards', sa.Column('working_directory', sa.String(length=1024), nullable=True))
    op.alter_column('columns', 'agent_workflow_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Which workflow to run when task enters: development, quick_development, architecture_only',
               existing_nullable=True)
    op.alter_column('tasks', 'agent_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Agent processing status: pending, architecture, development, review, completed, failed',
               existing_nullable=True)
    op.alter_column('tasks', 'current_execution_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to the current/latest agent execution',
               existing_nullable=True)
    op.alter_column('tasks', 'agent_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional agent-related metadata',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'agent_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional agent-related metadata',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tasks', 'current_execution_id',
               existing_type=sa.UUID(),
               comment='Reference to the current/latest agent execution',
               existing_nullable=True)
    op.alter_column('tasks', 'agent_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Agent processing status: pending, architecture, development, review, completed, failed',
               existing_nullable=True)
    op.alter_column('columns', 'agent_workflow_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Which workflow to run when task enters: development, quick_development, architecture_only',
               existing_nullable=True)
    op.drop_column('boards', 'working_directory')
    op.alter_column('agent_outputs', 'duration_ms',
               existing_type=sa.INTEGER(),
               comment='Execution duration in milliseconds',
               existing_nullable=True)
    op.alter_column('agent_outputs', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment='Total tokens used in this agent call',
               existing_nullable=True)
    op.alter_column('agent_outputs', 'files_created',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of files created/modified by agent',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_outputs', 'output_structured',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Parsed structured output',
               existing_nullable=True)
    op.alter_column('agent_outputs', 'output_content',
               existing_type=sa.TEXT(),
               comment='Raw text output from the agent',
               existing_nullable=True)
    op.alter_column('agent_outputs', 'input_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Input provided to the agent',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_outputs', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='pending, running, completed, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('agent_outputs', 'phase',
               existing_type=sa.VARCHAR(length=50),
               comment='architecture, development, review',
               existing_nullable=False)
    op.alter_column('agent_outputs', 'agent_name',
               existing_type=sa.VARCHAR(length=100),
               comment='software-architect, software-developer, code-reviewer, queen-coordinator',
               existing_nullable=False)
    op.alter_column('agent_executions', 'result_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Summary of execution results',
               existing_nullable=True)
    op.alter_column('agent_executions', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Execution context and configuration',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_executions', 'iteration',
               existing_type=sa.INTEGER(),
               comment='Current iteration count for feedback loops',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_executions', 'current_phase',
               existing_type=sa.VARCHAR(length=50),
               comment='Current workflow phase: architecture, development, review',
               existing_nullable=True)
    op.alter_column('agent_executions', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='pending, running, completed, failed, cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('agent_executions', 'workflow_type',
               existing_type=sa.VARCHAR(length=50),
               comment='development, quick_development, architecture_only',
               existing_nullable=False)
    # ### end Alembic commands ###
